---
- name: Confirm no existing printer config
  ansible.builtin.file:
    path: /home/"{{ klipper_user }}"/printer_data/printer.cfg
    state: absent

- name: Clone klipper config
  ansible.builtin.git:
    repo: "{{ klipper_config_git }}"
    dest: /home/"{{ klipper_user }}"/klipper_config
    version: "{{ klipper_config_version }}"
    update: true

- name: Create Klipper Config symbolic link
  ansible.builtin.file:
    src: /home/"{{ klipper_user }}"/klipper_config/"{{ klipper_config_file }}"
    dest: /home/"{{ klipper_user }}/"printer_data/printer.cfg
    owner: "{{ klipper_user }}"
    group: "{{ klipper_user }}"
    state: link
