- name: Install Required Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-virtualenv
    - python3-dev
    - python3-dev
    - libffi-dev
    - build-essential
    - libncurses-dev
    - avrdude
    - gcc-avr
    - binutils-avr
    - avr-libc
    - stm32flash
    - dfu-util
    - libnewlib-arm-none-eabi
    - gcc-arm-none-eabi
    - binutils-arm-none-eabi
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - python3-virtualenv
    - python3-dev
    - libopenjp2-7
    - python3-libgpiod
    - curl
    - libcurl4-openssl-dev
    - libssl-dev
    - liblmdb-dev
    - libsodium-dev
    - zlib1g-dev
    - libjpeg-dev
    - packagekit
    - wireless-tools
    - nginx ## Installing NGINX as part of this package, may cause problems if using another NGINX Ansible Role