- name: Install Required Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-virtualenv
    - python3-dev
    - python3-dev
    - libffi-dev
    - build-essential
    - libncurses-dev
    - avrdude
    - gcc-avr
    - binutils-avr
    - avr-libc
    - stm32flash
    - dfu-util
    - libnewlib-arm-none-eabi
    - gcc-arm-none-eabi
    - binutils-arm-none-eabi
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - python3-virtualenv
    - python3-dev
    - libopenjp2-7
    - python3-libgpiod
    - curl
    - libcurl4-openssl-dev
    - libssl-dev
    - liblmdb-dev
    - libsodium-dev
    - zlib1g-dev
    - libjpeg-dev
    - packagekit
    - wireless-tools
    - nginx ## Installing NGINX as part of this package, may cause problems if using another NGINX Ansible Role

- name: Clone klipper
  ansible.builtin.git:
    repo: https://github.com/KevinOConnor/klipper.git
    dest: /home/server/klipper
    update: yes

- name: Create data directory
  ansible.builtin.file:
    path: /home/server/printer_data/
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Create config directory
  ansible.builtin.file:
    path: /home/server/printer_data/config
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Create log directory
  ansible.builtin.file:
    path: /home/server/printer_data/logs
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Create gcode directory
  ansible.builtin.file:
    path: /home/server/printer_data/gcodes
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Create systemd directory
  ansible.builtin.file:
    path: /home/server/printer_data/systemd
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Create comms directory
  ansible.builtin.file:
    path: /home/server/printer_data/comms
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Clone klipper config
  ansible.builtin.git:
    repo: https://github.com/Capp3/klipper_config.git
    dest: /home/server/klipper_config
    version: main
    update: yes

- name: Create Klipper Config symbolic link
  ansible.builtin.file:
    src: /home/server/klipper_config/tevo_sbase.cfg
    dest: /home/server/printer_data/printer.cfg
    owner: server
    group: server
    state: link

- name: Install klippy into the specified (virtualenv), using Python 3
  ansible.builtin.pip:
    name: klipper
    virtualenv: /home/server/klippy-env
    virtualenv_command: virtualenv-3
    requirements: /home/server/klipper/scripts/klippy-requirements.txt

- name: Copy Klipper Service file
  ansible.builtin.copy:
    src: files/klipper.service
    dest: /etc/systemd/system/klipper.service
    owner: root
    group: root
    mode: '0755'

- name: Copy Klipper Env file
  ansible.builtin.copy:
    src: files/klipper.file
    dest: /home/server/printer_data/systemd/klipper.env
    owner: server
    group: server
    mode: '0755'

- name: Enable Klipper Service
  ansible.builtin.systemd:
    name: klipper.service
    enabled: true
    state: started

- name: Clone Moonraker
  ansible.builtin.git:
    repo: https://github.com/Arksine/moonraker.git
    dest: /home/server/moonraker
    update: yes

- name: Install Moonraker into the specified (virtualenv), using Python 3
  ansible.builtin.pip:
    name: moonraker
    virtualenv: /home/server/moonraker-env
    virtualenv_command: virtualenv-3
    requirements: /home/server/moonraker/scripts/moonraker-requirements.txt

- name: Copy Moonraker config file
  ansible.builtin.copy:
    src: files/moonraker.conf
    dest: /home/server/printer_data/config/moonraker.conf
    owner: server
    group: server
    mode: '0755'

- name: Copy Moonraker service file
  ansible.builtin.copy:
    src: files/moonraker.service
    dest: /etc/systemd/system/moonraker.service
    owner: root
    group: root
    mode: '0755'

- name: Copy Moonraker env file
  ansible.builtin.copy:
    src: files/moonraker.file
    dest: /home/server/printer_data/systemd/moonraker.env
    owner: server
    group: server
    mode: '0755'

- name: Enable Moonraker Service
  ansible.builtin.systemd:
    name: moonraker.service
    enabled: true
    state: started

- name: Execute Moonraker Script
  ansible.builtin.shell: /home/server/moonraker/scripts/set-policykit-rules.sh >> moonpolicylog.txt
  args:
    chdir: /home/server

- name: Copy Mainsail Nginx file
  ansible.builtin.copy:
    src: files/mainsail.nginx
    dest: /etc/nginx/sites-available/mainsail
    owner: root
    group: root
    mode: '0755'

- name: Copy Mainsail Upstreams file
  ansible.builtin.copy:
    src: files/moonraker.upstreams
    dest: /etc/nginx/conf.d/upstreams.conf
    owner: root
    group: root
    mode: '0755'

- name: Copy Mainsail Vars file
  ansible.builtin.copy:
    src: files/moonraker.vars
    dest: /etc/nginx/conf.d/common_vars.conf
    owner: root
    group: root
    mode: '0755'

- name: Create data directory
  ansible.builtin.file:
    path: /home/server/mainsail
    state: directory
    mode: '0775'
    owner: server
    group: server

- name: Remove default Nginx Site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Klipper Config symbolic link
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mainsail
    dest: /etc/nginx/sites-enabled/
    owner: root
    group: root
    state: link

- name: Enable Moonraker Service
  ansible.builtin.systemd:
    name: moonraker.service
    enabled: true
    state: reloaded

- name: Download & Unarchive Mainsail 
  ansible.builtin.unarchive:
    src: https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip
    dest: /home/server/mainsail
    remote_src: yes
