---
- name: Reload Klipper Service
  ansible.builtin.systemd:
    name: klipper.service
    enabled: true
    state: reloaded

- name: Reload Moonraker Service
  ansible.builtin.systemd:
    name: moonraker.service
    enabled: true
    state: reloaded

- name: Update klipper config
  ansible.builtin.git:
    repo: {{ klipper_config_git }}
    dest: /home/{{ klipper_user }}/klipper_config
    update: yes
  when: klipper_config_git is defined