FROM python:3.11.4-bookworm

ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=server

WORKDIR /home/server

RUN groupadd --gid 1000 $USERNAME && \
    useradd --uid 1000 --gid 1000 -m $USERNAME
## Make sure to reflect new user in PATH
ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"

RUN apt-get update && \
  apt-get install -y gcc libkrb5-dev && \
  apt-get install python3-pip -y && \
  pip3 install --upgrade pip && \
  pip3 install --upgrade virtualenv && \
  pip3 install pywinrm[kerberos] && \
  apt install krb5-user -y && \ 
  pip3 install pywinrm && \
  pip3 install ansible && \
  pip3 install ansible-lint

USER $USERNAME  